Make an extremely aggrivating concession for Visual C++ to allow gmtl::makeDirCos<T>() to be accessible from Python on Windows.  From what I can tell, Visual C++ cannot determine the full type instantiation of a templated type when it is used as a default function parameter value.  For example:
template<typename T>
void f(const gmtl::Vec<T, 3>& v = gmtl::Vec<T, 3>(0, 0, 0))
{
   // Do something ...
}

Visual C++ 7.1 and 8.0 Beta 2 both complain that gmtl::Vec<T, 3> has no
constructors, which normally indicates that the type in question is not
fully declared before being used (see error C2514).

There may be a better solution to this that could come in different forms.
I would like very much to see this revision backed out at some point in
the future.  For now, however, this fixes the last remaining problem with
the PyGMTL interface not being consistent across platforms, and that is a
much bigger issue than simplicity of code.


git-svn-id: https://ggt.svn.sourceforge.net/svnroot/ggt/trunk/GGT/modules/GMTL@1034 6382ae23-ed94-47d5-a97d-470f0bc4535f